region               = "us-west-2"
vpc_id               = "vpc-XXXXXXXXXXXXXXXXX"
private_subnet_id    = "subnet-XXXXXXXXXXXXXXXXX"
agent_image_uri      = "XXXXXXXXXXXX.dkr.ecr.us-west-2.amazonaws.com/datagrail-rdd-agent:v0.7.6"
cluster_arn          = "arn:aws:ecs:us-west-2:XXXXXXXXXXXX:cluster/datagrail-rdd-agent-cluster"
create_vpc_endpoints = "false"
